In [1]:
import pandas as pd

resultados_df = pd.read_csv("results.csv")
pilotos_df = pd.read_csv("drivers.csv")

In [2]:
# filtrar colunas relevantes
colunas_pilotos = ["driverId", "forename", "surname", "nationality"]
pilotos_df = pilotos_df[colunas_pilotos]
colunas_pilotos_renomeados = {
    "driverId": "id_piloto",
    "forename": "nome",
    "surname": "sobrenome",
    "nationality": "nacionalidade"
}
pilotos_df = pilotos_df.rename(columns=colunas_pilotos_renomeados)
pilotos_df["nome_completo"] = pilotos_df["nome"] + " " + pilotos_df["sobrenome"]
pilotos_df.head()

   id_piloto      nome   sobrenome nacionalidade      nome_completo
0          1     Lewis    Hamilton       British     Lewis Hamilton
1          2      Nick    Heidfeld        German      Nick Heidfeld
2          3      Nico     Rosberg        German       Nico Rosberg
3          4  Fernando      Alonso       Spanish    Fernando Alonso
4          5    Heikki  Kovalainen       Finnish  Heikki Kovalainen

In [3]:
# resultados relevantes
resultados_df.head()
colunas_resultados = ["raceId", "driverId", "positionOrder"]
resultados_df = resultados_df[colunas_resultados]
colunas_resultados_renomeados = {
    "raceId": "id_corrida",
    "driverId": "id_piloto",
    "positionOrder": "posicao_final"
}
resultados_df = resultados_df.rename(columns=colunas_resultados_renomeados)
resultados_df.head()

   id_corrida  id_piloto  posicao_final
0          18          1              1
1          18          2              2
2          18          3              3
3          18          4              4
4          18          5              5

In [7]:
# filtrar somente vencedores (posição final = 1)
eh_vencedor = resultados_df["posicao_final"] == 1
vencedores_df = resultados_df[eh_vencedor]
vencedores_df.head()

    id_corrida  id_piloto  posicao_final
0           18          1              1
22          19          8              1
44          20         13              1
66          21          8              1
88          22         13              1

In [11]:
# mesclar os DataFrames de resultados e pilotos
vencedores_com_pilotos_df = pd.merge(
    vencedores_df, 
    pilotos_df,
    on="id_piloto",
)
vencedores_com_pilotos_df.head()
vencedores_com_pilotos_df.shape

(1128, 7)

In [19]:
# Agrupar por quantidade de vitórias
agrupado_por_vitorias_df = vencedores_com_pilotos_df.groupby(
    ["id_piloto", "nome_completo", "nacionalidade"]
).size().reset_index(name="vitorias")
# ordenar por mais vitorias - descendente
agrupado_por_vitorias_df = agrupado_por_vitorias_df.sort_values(
    by="vitorias", ascending=False
)
agrupado_por_vitorias_df.head(10)

     id_piloto       nome_completo nacionalidade  vitorias
0            1      Lewis Hamilton       British       105
15          30  Michael Schumacher        German        91
107        830      Max Verstappen         Dutch        63
11          20    Sebastian Vettel        German        53
29         117         Alain Prost        French        51
27         102        Ayrton Senna     Brazilian        41
2            4     Fernando Alonso       Spanish        32
26          95       Nigel Mansell       British        31
64         328      Jackie Stewart       British        27
73         373           Jim Clark       British        25